-----DATA PREPARATION & UNDERSTANDING-----


--1.what is the total number of rows in each of the 3 tables in the database?--

select COUNT(*) as Total_rows_Customer from dbo.Customer 
union all
Select COUNT(*) as Total_rows_Prod from dbo.prod_cat_info
union all
select COUNT(*) as Total_rows_Transtions from dbo.Transactions


--2.what is the total number of transactions that have a return?--

Select COUNT(distinct transaction_id) as Total_Returns from dbo.Transactions where qty<0


--3.As you would have noticed,the dates provided across datasets are not in correct format. As first steps, please convert the data Variables 
--into valid date formats before proceeding ahead.

Update Customer
set DOB = CONVERT(date, DOB, 103)
Alter table customer
Alter column DOB date

update Transactions
set tran_date = CONVERT(date, tran_date, 103)
Alter table transactions
Alter column tran_date date


--4.What is the time range of the transaction data available for analysis?show the output in number of days,months and years simultaneously in different columns.

select 
DATEDIFF(DAY,MIN(tran_date),MAX(tran_date))as days_diff,
DATEDIFF(month,MIN(tran_date),MAX(tran_date))as month_diff,
DATEDIFF(year,MIN(tran_date),MAX(tran_date))as years_diff 
from Transactions


--5.Which product category does the sub category DIY belong to?

select prod_cat,prod_subcat from prod_cat_info
where prod_subcat='DIY'

--------------DATA ANALYSIS---------------


--1.which channel is most frequently used for transactions?

select top 1 Store_type , COUNT( distinct transaction_id) as Channel from Transactions
group by Store_type
order by Channel desc


--2.What is the count of male & female customers in database?

select GENDER,COUNT(GENDER) as [Count_of_(M/F)] from Customer
group by GENDER
having GENDER in ('F','M')
order by [Count_of_(M/F)] DESC


--3.From which city do we have the maximum number of customers how many? 

Select top 1 city_code, COUNT(city_code) as Max_Customers from Customer
group by city_code
order by Max_Customers desc


--4.How many subcategories are there under the books category? 

select prod_cat, count(prod_subcat) as Sub_Category from prod_cat_info
group by prod_cat
having prod_cat='Books'
order by Sub_Category


--5.What is the maximum quantity of products ever ordered? 

select MAX(Qty) as Maximum_Qty from Transactions


--6.What is the net total revenue generated in categories electronics and books? 
 
select 'electronics+books' as category ,sum(total_amt) as net_revenue from prod_cat_info A 
join Transactions B on A.prod_cat_code=B.prod_cat_code
where prod_cat IN ('ELECTRONICS','BOOKS')


--7.How many customers have greater than 10 transactions with us, excluding returns?

select COUNT(*) as [Coustomer_Transtions > 10] from (select cust_id,COUNT(cust_id) as Count_Transactions from Transactions
where Qty>0
group by cust_id
having count(cust_id)>10 ) Toatl_cust


--8.What is the combined revenue earned  from the electronics and clothing categories from flagship stores? 

select 'Electronics & Clothing' as Products , ceiling(SUM(total_amt))Revenue from prod_cat_info A
left join Transactions B on A.prod_cat_code=B.prod_cat_code and B.prod_subcat_code=A.prod_sub_cat_code
where prod_cat in ('Electronics','Clothing') and Store_type='flagship store'


--9.What is the total revenue generated from "male" customers in "electronics" category? Output should display total revenue by prod sub- cat.

select gender,prod_cat,ROUND(sum(total_amt),2) as revenue from Customer A join Transactions B on A.customer_Id=B.cust_Id join prod_cat_info C 
on C.prod_cat_code=B.prod_cat_code
where gender='M'and prod_cat='Electronics'
group by gender,prod_cat


--10.What is percentage of sales and returns by product subcategory display only top 5 subcategories in terms of sales?

Select Top 5 prod_subcat,Sum(case WHEN total_amt > 0 THEN 1 ELSE 0 END) As 'sales',
sum(case WHEN total_amt> 0 THEN 1.0 ELSE 0 END) /count(*) *100 As 'Sale_percent',
sum(case WHEN total_amt < 0 THEN 1 ELSE 0 END) As 'Returns',
sum(case WHEN total_amt < 0 THEN 1.0 ELSE 0 END) /count(*) *100 As 'Return_percent' From Transactions As T1
INNER JOIN prod_cat_info As P1  ON T1.prod_subcat_code = P1.prod_sub_cat_code and T1.prod_cat_code = P1.prod_cat_code
Group By prod_subcat
Order By sales desc


--11.For all customers aged between 25 to 35 years find what is the net total revenue generated by these customers
--in last 30 days of transactions from maximum transaction date available in the data?

select DOB,DATEDIFF(year,DOB,GETDATE()) as [age_b/w_25-35],sum(total_amt) as total_revenue,DATEADD(day,-30,MAX(tran_date)) as last_tran_date from customer A
join Transactions B on A.customer_Id=B.cust_id
Where DATEDIFF(year,DOB,GETDATE()) between 25 and 35
Group by DOB,tran_date,DATEDIFF(year,DOB,GETDATE())
Order by last_tran_date


--12.Which product category has seen the maximum value of returns in the last three months of transactions? 
 
Select top 1 * from (
Select prod_cat,sum(qty) as Returns,DATEADD(month,-3,MAX(tran_date)) as [last_3_month] from prod_cat_info A join Transactions B on A.prod_cat_code=B.prod_cat_code
Group by prod_cat,Qty
Having sum(qty)<0)
prod_cat_max
Order by Returns


--13.Which store type sells the maximum for rates by value of sales amount by quantity sold? 

select store_type from (
Select TOP 1 STORE_TYPE, sum(qty) AS SUM_QTY,SUM(TOTAL_AMT) AS Total_SUM FROM TRANSACTIONS
Group BY STORE_TYPE
Order BY SUM_QTY DESC, Total_SUM DESC)max_store_type


--14.What are the categories for which average revenue is above the overall average?

Select prod_cat,avg(total_amt)as [AVG_SALES > AVG_TOTAL_SALES],(select avg(total_amt) as avg_revenue from Transactions) AS AVG_TOTAL_SALES  from prod_cat_info A
join Transactions B on A.prod_cat_code=B.prod_cat_code
Group by prod_cat
Having round(avg(total_amt),2)>(select avg(total_amt) as avg_revenue from Transactions)


--15.Find the average and total revenue by each sub category for the categories which are among top 5 categories in terms of quantity sold.

Select Top 5 * from (
Select prod_cat,prod_subcat,sum(Qty) as sum_qty,AVG(total_amt) as avg_sales,total_amt as total_revenue from prod_cat_info A
left  join Transactions B on A.prod_cat_code=B.prod_cat_code and A.prod_sub_cat_code=B.prod_subcat_code
Group by prod_cat,prod_subcat,total_amt
Having SUM(qty)>0)a
Order by  sum_qty desc
	
